# Generated by Django 3.2.5 on 2021-07-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityairqualityinfo',
            name='aqi',
            field=models.CharField(max_length=100, null=True, verbose_name='实时AQI'),
        ),
        migrations.AddField(
            model_name='cityairqualityinfo',
            name='aqi_average',
            field=models.IntegerField(null=True, verbose_name='平均AQI'),
        ),
        migrations.AddField(
            model_name='cityairqualityinfo',
            name='co',
            field=models.CharField(max_length=100, null=True, verbose_name='CO'),
        ),
        migrations.AddField(
            model_name='cityairqualityinfo',
            name='co_24',
            field=models.IntegerField(null=True, verbose_name='CO_24h'),
        ),
        migrations.AddField(
            model_name='cityairqualityinfo',
            name='no2',
            field=models.CharField(max_length=100, null=True, verbose_name='NO2'),
        ),
        migrations.AddField(
            model_name='cityairqualityinfo',
            name='no2_24',
            field=models.IntegerField(null=True, verbose_name='NO2_24h'),
        ),
        migrations.AddField(
            model_name='cityairqualityinfo',
            name='o3',
            field=models.CharField(max_length=100, null=True, verbose_name='O3'),
        ),
        migrations.AddField(
            model_name='cityairqualityinfo',
            name='o3_24',
            field=models.IntegerField(null=True, verbose_name='O3_24h'),
        ),
        migrations.AddField(
            model_name='cityairqualityinfo',
            name='o3_8h',
            field=models.CharField(max_length=100, null=True, verbose_name='O3_8h'),
        ),
        migrations.AddField(
            model_name='cityairqualityinfo',
            name='o3_8h_24',
            field=models.IntegerField(null=True, verbose_name='O3_8h_24h'),
        ),
        migrations.AddField(
            model_name='cityairqualityinfo',
            name='pm10',
            field=models.CharField(max_length=100, null=True, verbose_name='PM10'),
        ),
        migrations.AddField(
            model_name='cityairqualityinfo',
            name='pm10_24',
            field=models.IntegerField(null=True, verbose_name='PM10_24h'),
        ),
        migrations.AddField(
            model_name='cityairqualityinfo',
            name='pm2_5',
            field=models.CharField(max_length=100, null=True, verbose_name='PM2.5'),
        ),
        migrations.AddField(
            model_name='cityairqualityinfo',
            name='pm2_5_24',
            field=models.IntegerField(null=True, verbose_name='PM2.5_24h'),
        ),
        migrations.AddField(
            model_name='cityairqualityinfo',
            name='so2',
            field=models.CharField(max_length=100, null=True, verbose_name='SO2'),
        ),
        migrations.AddField(
            model_name='cityairqualityinfo',
            name='so2_24',
            field=models.IntegerField(null=True, verbose_name='SO2_24h'),
        ),
    ]
