# Generated by Django 3.2.5 on 2021-07-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_data', '0002_auto_20210723_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cityairqualityinfo',
            old_name='aqi_average',
            new_name='aqi_24h',
        ),
        migrations.RenameField(
            model_name='cityairqualityinfo',
            old_name='no2_24',
            new_name='no2_24h',
        ),
        migrations.RenameField(
            model_name='cityairqualityinfo',
            old_name='o3_24',
            new_name='o3_24h',
        ),
        migrations.RenameField(
            model_name='cityairqualityinfo',
            old_name='o3_8h_24',
            new_name='o3_8h_24h',
        ),
        migrations.RenameField(
            model_name='cityairqualityinfo',
            old_name='pm10_24',
            new_name='pm10_24h',
        ),
        migrations.RenameField(
            model_name='cityairqualityinfo',
            old_name='pm2_5_24',
            new_name='pm2_5_24h',
        ),
        migrations.RenameField(
            model_name='cityairqualityinfo',
            old_name='so2_24',
            new_name='so2_24h',
        ),
        migrations.RemoveField(
            model_name='cityairqualityinfo',
            name='co_24',
        ),
        migrations.AddField(
            model_name='cityairqualityinfo',
            name='co_24h',
            field=models.FloatField(null=True, verbose_name='CO_24h'),
        ),
    ]
