# Generated by Django 3.2.5 on 2021-07-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_data', '0003_auto_20210723_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityairqualityinfo',
            name='aqi_24h',
            field=models.CharField(max_length=100, null=True, verbose_name='平均AQI'),
        ),
        migrations.AlterField(
            model_name='cityairqualityinfo',
            name='co_24h',
            field=models.CharField(max_length=100, null=True, verbose_name='CO_24h'),
        ),
        migrations.AlterField(
            model_name='cityairqualityinfo',
            name='no2_24h',
            field=models.CharField(max_length=100, null=True, verbose_name='NO2_24h'),
        ),
        migrations.AlterField(
            model_name='cityairqualityinfo',
            name='o3_24h',
            field=models.CharField(max_length=100, null=True, verbose_name='O3_24h'),
        ),
        migrations.AlterField(
            model_name='cityairqualityinfo',
            name='o3_8h_24h',
            field=models.CharField(max_length=100, null=True, verbose_name='O3_8h_24h'),
        ),
        migrations.AlterField(
            model_name='cityairqualityinfo',
            name='pm10_24h',
            field=models.CharField(max_length=100, null=True, verbose_name='PM10_24h'),
        ),
        migrations.AlterField(
            model_name='cityairqualityinfo',
            name='pm2_5_24h',
            field=models.CharField(max_length=100, null=True, verbose_name='PM2.5_24h'),
        ),
        migrations.AlterField(
            model_name='cityairqualityinfo',
            name='so2_24h',
            field=models.CharField(max_length=100, null=True, verbose_name='SO2_24h'),
        ),
    ]
