# Generated by Django 3.2.5 on 2021-07-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_data', '0004_auto_20210723_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityairqualityinfo',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
