# Generated by Django 3.2.5 on 2021-07-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_data', '0005_alter_cityairqualityinfo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityairqualityinfo',
            name='date',
            field=models.IntegerField(null=True, verbose_name='日期'),
        ),
    ]
